---
defaultNamespace: external-dns
helm:
  chart: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
  version: v1.7.1
  values:
    interval: 1m
    triggerLoopOnEvent: true
    policy: sync
    extraArgs:
      - --zone-id-filter=$(HOSTED_ZONE_ID)
      - --aws-zone-type=public
      - --aws-zones-cache-duration=24h
      - --txt-owner-id=$(CLUSTER_NAME)
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: external-dns-route53
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: external-dns-route53
          key: aws_secret_access_key
    - name: HOSTED_ZONE_ID
      valueFrom:
        secretKeyRef:
          name: external-dns-route53
          key: hosted_zone_id
    - name: CLUSTER_NAME
      valueFrom:
        configMapKeyRef:
          name: cluster-name
          key: cluster_name
