---
defaultNamespace: metallb-system
helm:
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: v0.11.0
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 140.252.146.88-140.252.146.89
