---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-hcp
spec:
  provider:
    vault:
      server: "https://vault-test.vault.f08d6cac-fa22-439d-a293-8b58a76c4714.aws.hashicorp.cloud:8200"
      path: secret
      namespace: admin
      version: v2
      auth:
        appRole:
          path: approle
          roleId: 3aaf5051-14a7-b941-acd4-1ef05b8fedb6
          secretRef:
            name: vault-approle
            namespace: external-secrets
            key: secret-id
