---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-dns-route53
  namespace: external-dns
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-hcp
    kind: ClusterSecretStore
  target:
    name: external-dns-route53
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: k8s/site/tu
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: k8s/site/tu
      property: aws_secret_access_key
  - secretKey: hosted_zone_id
    remoteRef:
      key: k8s/site/tu
      property: hosted_zone_id
